services:
  app:
    container_name: pgw-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pgw-app
    ports:
      - '3031:3031'
    working_dir: /app
    volumes:
      - ../logs:/app/logs

  redis:
    container_name: pgw-redis
    image: redis:6.2.13
    restart: always
    # ports:
    #   - '6379:6379'
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
